// playground/vite-react/src/App.tsx
import SymbolSprite from 'unplugin-svg-sprite/symbol'

import ViteSvg from '~svg-sprite/symbol/src/assets/raw/vite'
import ReactSvg from '~svg-sprite/symbol/src/assets/raw/react'
import VercelSvg from '~svg-sprite/symbol/src/assets/raw/vercel'
import VercelCopySvg from '~svg-sprite/symbol/src/assets/vercel'

import './App.less'

function App() {
  return (
    <div>
      <SymbolSprite />
      <div className='flex'>
        <ReactSvg />
        <VercelSvg />
        <ViteSvg />
        <VercelCopySvg />
      </div>
    </div>
  )
}

export default App

// examples/nuxtjs/app.vue
<template>
  <SymbolSprite />
  <div>
    <img src="~/assets/vercel.svg" alt="Discover Nuxt 3" style="width: 48px" />
    <ViteSvg />
    <ReactSvg />
    <VercelSvg />
    <VercelCopySvg />
  </div>
</template>

<script setup>
import SymbolSprite from '~svg-sprite/symbol'
import VercelSvg from '@/assets/vercel.svg?symbol'
import ViteSvg from '@/assets/raw/vite.svg?symbol'
import ReactSvg from '@/assets/raw/react.svg?symbol'
import VercelCopySvg from '@/assets/vercel.svg?symbol'
</script>
